Module = "crawler"
# dev | test | prod
# Env = "dev"

NoInject = ["Apollo","Etcd"]


[configCenter]
Watch  = true

[configCenter.nacos]
Addr = "nacos.local.org"
Group = "hoper"

[configCenter.local]
ReloadType = "fsnotify"


[dev]
LocalConfigName = "local.toml"

[test]
NacosTenant = "b5b476ab-774f-4637-a8bf-e915635b4b24"

[prod]
NacosTenant = ""
