# 多域名区分，与grpc一致，grpc没法主动在uri加前缀
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: hoper-api
  namespace: default
spec:
  http:
    - name: hoper
      match:
        hosts:
          - api.hoper.xyz
        paths:
          - /*
      backends:
        - serviceName: hoper
          servicePort: 80
          resolveGranularity: service
      websocket: true
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: hoper-grpc
  namespace: default
spec:
  http:
    - name: hoper-grpc
      match:
        hosts:
          - grpc.hoper.xyz
        paths:
          - /*
      backends:
        - serviceName: hoper
          servicePort: 8090
          resolveGranularity: service
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
