apiVersion: v1
kind: Service
metadata:
  name: hoper
  labels:
    app: hoper
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8090
    - name: grpc
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: hoper
---
# 不需要
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: hoper
spec:
  loadbalancer:
    type: roundrobin
  portLevelSettings:
    - port: 80
      scheme: http
    - port: 8090
      scheme: grpc
