[package]
name = "p_macro"
version = "0.1.0"
authors = ["贾一饼 <lby.i@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[features]

[dependencies]
syn = { version = "1.0.30", features = ["full"] }
quote = "1.0.6"
proc-macro2 = "1.0.18"
actix-web = "2"
actix-rt = "1"
rocket = "0.4.2"
serde = "*"
