title = "user-config"

NoInit = ["Cache","Apollo","Consul"]

[server]
Protocol = "https"
Domain =  "user.hoper.xyz"
Port = ":8090"
ReadTimeout = 60
WriteTimeout = 60

[customize]
GrpcService = {user = "localhost:8080", note = "localhost:8090"}
Volume = "../../data"

TokenMaxAge = 86400

PageSize = 10
JwtSecret = "233"


#文件
UploadDir = "/upload"

# MB
UploadMaxSize = 10
UploadAllowExt = [".jpg",".jpeg",".png",".gif"]

LuosimaoVerifyURL ="https://captcha.luosimao.com/api/site_verify"
LuosimaoAPIKey ="f4a1c65ee13911b7bb9f902655c773a6"

QrCodeSaveDir = "/qrcode"
PrefixUrl =""
FontSaveDir ="/font"

CrawlerName =""

[database]
Type = ""
User = ""
Password = ""
Host = ""
Port = 3306
Charset = "utf8mb4"
Database = "test"
TablePrefix =""
MaxIdleConns = 5
MaxOpenConns = 10


[redis]
Addr = ""
Password =""
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200

#日志
[log]
Level = "debug"
Caller = true
OutputPaths = {console = ["stderr"],json = []}


#邮件
[mail]
Host = "smtp.qq.com"
Port = ":465"
From =  ""
Password = ""

[apollo]
Addr = "192.168.1.212:8080"
AppId = "hoper"
Cluster = "default"
NameSpace = ["application"]

[consul]
Addr = "192.168.1.212:8500"
