title = "user"

[server]
Host =  "user.hoper.xyz"
Port = ":8000"
ReadTimeout = 60
WriteTimeout = 60

PassSalt = "%*~&*G(Ysa-jyb"
TokenSecret = "hjoihiahDAW2iofjiJPO"
TokenMaxAge = 86400

PageSize = 10
JwtSecret = "233"

RuntimeRootPath =""
#文件
UploadDir = "../../static/upload"
UploadPath = "/static/upload"
# MB
UploadMaxSize = 5
UploadAllowExt = [".jpg",".jpeg",".png",".gif"]

#邮件
MailHost = "smtp.qq.com"
MailPort = ":465"
MailUser =  "lby.i@qq.com"
MailPassword = "123456"

LuosimaoVerifyURL ="https://captcha.luosimao.com/api/site_verify"
LuosimaoAPIKey ="f4a1c65ee13911b7bb9f902655c773a6"

QrCodeSavePath = "../../static/qrcode"
PrefixUrl =""
FontSavePath ="../../static/font"

CrawlerName =""
[database]
Type = "postgres"
#Type = mysql
#User = root
User = "postgres"
Password = "123456"
Host = "hoper.xyz"
#Port = 3306
Port = 5432
Charset = "utf8"
Database = "hoper_test"
TablePrefix =""
MaxIdleConns = 5
MaxOpenConns = 10

[redis]
Addr = "hoper.xyz:6379"
Password =""
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200

#日志
[log]
Level = 0
Skip = true
OutputPaths = {console = ["stderr"],json = []}