greeting:
  message: hello
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: "123456"
    jdbc:
      url: jdbc:postgresql://192.168.1.212:5432/postgres
      max-size: 20
    reactive: false
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true

logging:
  level:
    root: info


