apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy
    group: proxy
  name: proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: proxy
        group: proxy
    spec:
      containers:
        - name: proxy
          image: jybl/proxy
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
          imagePullPolicy: IfNotPresent
