apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
  labels:
    app: proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: proxy