apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
namePrefix: dev-
nameSuffix: "-001"

resources:
  - deployment.yaml
  - service.yaml

vars:
  - name: MY_SERVICE_NAME
    objref:
      kind: Service
      name: my-nginx
      apiVersion: v1