Module = "gateway"

NoInit = ["Cache","Apollo","Consul"]

NacosAddr = "192.168.1.212:9001"
NacosGroup = "hoper"
NacosDataId = "gateway"

[iris]
DisableStartupLog= false
DisableInterruptHandler= false
DisablePathCorrection= true
EnablePathEscape= false
FireMethodNotAllowed= false
DisableBodyConsumptionOnUnmarshal= false
DisableAutoFireStatusCode= false
TimeFormat= "2006-01-02 15:04:05"
Charset= "UTF-8"
EnableOptimizations= true

#env
[dev]
Tenant = "e0119132-f523-4a84-bd42-7830235eb9cf"

[test]
Tenant = ""

[prod]
Tenant = ""
