spring:
  datasource:
    url: jdbc:mysql://192.168.1.212:3306/test
    username: web
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#webApi扫描包路径
web-api-packages: xyz.hoper.api
#异步服务扫描包路径
async-service-impl-packages: xyz.hoper.service.impl
#Http服务器端口号
http-server-port: 8090
#工作线程池大小
worker-pool-size: 40
#异步服务实例数，建议与CPU核数相同
async-service-instances: 3