[database]
Type = "mysql"
#User = root
User = "web"
Password = "123456"
Host = "192.168.1.212"
Port = 3306
Charset = "utf8"
Database = "test"
TablePrefix =""
MaxIdleConns = 5
MaxOpenConns = 10

[redis]
Host = "192.168.1.204:6379"
Password ="123456"
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200