Module = "hoper"
# dev | test | prod
# Env = "dev"

[dev]
configType = "local"
Watch  = true
NoInject = ["Apollo","Etcd", "Es"]

[dev.local]
Debug = true
ConfigPath = "local.toml"
ReloadType = "fsnotify"

[dev.http]
Interval = 100
Url = "http://localhost:6666/local.toml"


[test]
configType = "nacos"
Watch  = true
NoInject = ["Apollo","Etcd", "Es"]

[test.nacos]
DataId = "pro"
Group = "DEFAULT_GROUP"

[[test.nacos.ServerConfigs]]
Scheme = "http"
IpAddr = "nacos.liov.xyz"
Port = 9000
GrpcPort = 10000

[test.nacos.ClientConfig]
NamespaceId = ""
username = "nacos"
password = "225567"
LogLevel = "debug"

[prod]

