Module = "hoper"
# dev | test | prod
# Env = "dev"

[dev]
configType = "local"
Watch  = true
NoInject = ["Apollo","Etcd", "Es"]
InjectVersion = 1
[dev.nacos]
Addr = "nacos.local.org"
Group = "hoper"

[dev.nacosv2]
DataId = "timepill"
Group = "DEFAULT_GROUP"

[[dev.nacosv2.ServerConfigs]]
Scheme = "http"
IpAddr = "xxx"
Port = 1000
GrpcPort = 2000

[dev.nacosv2.ClientConfig]
NamespaceId = ""
username = "xxx"
password = "xxx"
LogLevel = "debug"

[dev.local]
ConfigName = "local.toml"
ReloadType = "fsnotify"

[test]

[prod]

