[package]
name = "timer"
version = "0.1.0"
authors = ["liov <lby.i@qq.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
tonic = "0.4.3"
prost = "0.7.0"
prost-types = "0.7.0"
tokio = { version = "1.5.0", features = ["full"] }
tokio-stream = { version =  "0.1", features = ["net"] }
async-stream = "0.3"
futures = { version = "0.3.15", default-features = false, features = ["alloc"] }
bytes = { version = "1.0.1", optional = true }
log = "0.4.14"
rand = "0.7.3"
slog = "2.7.0"
slog-async = "2.6.0"
slog-stdlog = "4.1.0"
slog-scope = "4.4.0"
slog-term = "2.8.0"

[dev-dependencies]
serde_json = "1.0.64"
serde = "1.0.126"
serde_derive = "1.0.126"
prost-derive = "0.7.0"



[build-dependencies]
tonic-build = "0.4.2"

[[bin]]
name = "server"
test = false