spring:
  r2dbc:
    url: r2dbc:postgresql://192.168.1.212:5432/postgres
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update


grpc:
  client:
    host: localhost
    port: 8090