title = "user-config"
#文件存储在Volume+Module下

Volume = "../../data"

[server]
Protocol = "https"
Domain =  "user.hoper.xyz"
Port = ":8080"
ReadTimeout = 60
WriteTimeout = 60

PassSalt = "%*~&*G(Ysa-jyb"
TokenSecret = "hjoihiahDAW2iofjiJPO"
TokenMaxAge = 86400

PageSize = 10
JwtSecret = "233"


#文件
UploadDir = "/upload"

# MB
UploadMaxSize = 5
UploadAllowExt = [".jpg",".jpeg",".png",".gif"]

LuosimaoVerifyURL ="https://captcha.luosimao.com/api/site_verify"
LuosimaoAPIKey ="f4a1c65ee13911b7bb9f902655c773a6"

QrCodeSaveDir = "/qrcode"
PrefixUrl =""
FontSaveDir ="/font"

CrawlerName =""
[database]
#Type = "postgres"
Type = "mysql"
User = "web"
Password = "123456"
Host = "192.168.1.212"
Port = 3306
TimeFormat = "2006-01-02 15:04:05.999"
Charset = "utf8mb4"
Database = "test"
TablePrefix =""
MaxIdleConns = 5
MaxOpenConns = 10

[redis]
Addr = "192.168.1.204:6379"
Password ="123456"
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200



#日志
[log]
Level = 0
Skip = true
OutputPaths = {console = ["stderr"],json = []}


#邮件
[mail]
Host = "smtp.qq.com"
Port = ":465"
User =  "lby.i@qq.com"
Password = "123456"
