name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-216.0.dev <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  async: ^2.10.0
  http: ^0.13.5
  dio: ^5.0.3
  webview_flutter: ^3.0.4
  webview_flutter_web: ^0.1.0+4
  ffi: ^2.0.1
  json_annotation: ^4.7.0
  flutter_markdown: ^0.6.13
  sqflite: ^2.2.0+3
  sqflite_common_ffi: ^2.2.0+1
  drift: ^2.2.0
  hive: ^2.2.3
  flutter_cache_manager: ^3.3.0
  shared_preferences: ^2.0.15
  get: ^4.6.5
  flutter_local_notifications: ^12.0.3
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  url_launcher: ^6.1.6
  geolocator: ^9.0.2
  protobuf: ^2.1.0
  grpc: ^3.1.0
  carousel_slider: ^4.1.1
  fl_chart: ^0.55.2
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  #flutter_swiper: ^1.1.6
  introduction_screen: ^3.0.2
  #image: ^3.0.2
  #photo_view: ^0.12.0
  #cached_network_image: ^3.1.0
  extended_text: ^9.1.2
  extended_text_field: ^10.1.1
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  syncfusion_flutter_charts: ^20.3.56
  camera: ^0.10.0+4
  qr_flutter: ^4.0.0
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  video_player: ^2.4.7
  just_audio: ^0.9.30
  extended_image: ^6.3.1
  animations: ^2.0.7
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  permission_handler: ^10.2.0
  args: ^2.3.1
  animate_do: ^2.1.0
  getwidget: ^3.0.1
  fluttertoast: ^8.1.1
  vector_math: ^2.1.4
  shelf_proxy: ^1.0.2
  feedback: ^2.5.0
  flex_color_scheme: ^6.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  logging: ^1.1.0
  flutter_slidable: ^2.0.0
  package_info_plus: ^3.0.1
  device_info_plus: ^8.0.0
  connectivity_plus: ^3.0.2
  share_plus: ^6.0.2
  infinite_scroll_pagination: ^3.2.0
  convex_bottom_bar: ^3.1.0+1
  power_image: 0.1.0-pre.2
  logger: ^1.1.0
  flame: ^1.4.0
# provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.21.0
  pigeon: ^4.2.5
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  protoc_plugin: ^20.0.1
  dart_style: ^2.2.3
  flutter_native_splash: ^2.2.14
  flutter_launcher_icons: ^0.10.0
  freezed: ^2.1.1
  power_image_ext: 2.5.3
  flutter_lints: ^2.0.1

dependency_overrides:
  #dart_style: ^2.1.1
  #args: ^2.0.0
  #platform: ^3.1.0
  ffi: ^2.0.1
  power_image_ext: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/weather/
    - assets/splash/splash.jpg
    - assets/dist/
    - assets/dist/css/
    - assets/dist/js/
    - assets/js/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.jpg"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/icon/icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48