Module = "test"
# dev | test | prod
# 命令行参数获取
# Env = "dev"
# 不需要注入的dao
NoInit = ["Cache","Apollo","Etcd"]


[nacos]
Addr = "nacos.default"
Group = "hoper"
Watch  = false

[gin]
TimeFormat= "2006-01-02 15:04:05"
Charset= "UTF-8"
EnableOptimizations= true

[dev]
# 本地开发配置文件
LocalConfigName = "local.toml"

[test]
NacosTenant = "b5b476ab-774f-4637-a8bf-e915635b4b24"

[prod]
NacosTenant = ""