Module = "user"
#dev | test | prod
Env = "dev"

NoInit = ["Cache","Apollo","Consul"]

NacosAddr = "192.168.1.212:9001"
NacosGroup = "hoper"
#NacosDataId = "user"

[gin]


[dev]
Tenant = "b5b476ab-774f-4637-a8bf-e915635b4b24"

[test]
Tenant = ""

[prod]
Tenant = ""