Module = "user"
# dev | test | prod
# Env = "dev"

NoInit = ["Cache","Apollo","Etcd"]

[nacos]
Addr = "nacos.default"
Group = "hoper"
# DataId = "user"
Watch  = false

[gin]


[dev]
NacosTenant = "b5b476ab-774f-4637-a8bf-e915635b4b24"

[test]
NacosTenant = ""

[prod]
NacosTenant = ""