[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[workspace]
members = [
    "hello",
    "hello_v2",
    "hello_v3"
]

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"