name: bilibili
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    tags:
      - bilibili-v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.3'
          check-latest: true
          cache: true
          cache-dependency-path: subdir/go.sum
      - run: |
          cd tools/server/bilibili
          go mod download
          go mod tidy
          go build -o bilibili ./cmd/record_fav.go
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:mysubdir"
          push: true
          tags: bilibili:latest